# -*- coding: utf-8 -*-
"""bioe400_testcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-DjMWC4DAvVYjzo0gP5WjxJMAWEFTP1
"""

from octorest import OctoRest
import time
import os
from itertools import chain, combinations

def make_client(url, apikey):
    #Creates and returns an instance of the OctoRest client with API key.
    try:
        client = OctoRest(url=url, apikey=apikey)
        return client
    except ConnectionError as ex:
        print(f"Connection error: {ex}")
        return None


def file_names(client):
    #Retrieves the G-code file names from the OctoPrint server and prints them. Just making sure its actually there
    message = "The GCODE files currently on the printer are:\n"
    try:
        for k in client.files()['files']:
            message += k['name'] + "\n"
        print(message)
    except Exception as ex:
        print(f"Failed to retrieve file names: {ex}")

def sleep(seconds):
    '''
    If recording, sleep for a given amount of seconds
    '''
    # if 'RECORD' in os.environ:
    time.sleep(seconds)

def cmd_wait_until(client, state):
    while client.state() != state:
        sleep(0.1)

def select_and_print_gcode(client, gcode_filename):
    try:
        # Retrieve the list of G-code files
        files = client.files()['files']

        # Check if the desired G-code file is in the list
        for file in files:
            if file['name'] == gcode_filename:
                # Select the G-code file and start printing
                client.select(gcode_filename, print=True)  # Make sure to use the correct path
                break
        else:
            raise Exception(f"GCode file '{gcode_filename}' not found.")

        # Wait for the printer to start printing
        cmd_wait_until(client, 'Printing')

        print(f"Successfully selected and started printing {gcode_filename}.")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    # URL where OctoPrint is running
    url = "http://localhost:4000"

    # Your actual API key (retrieve from OctoPrint settings)
    apikey = "560EA2EF07AD48F597D7B2DD0A4AD4B9"

    # Create an OctoRest client to interact with OctoPrint, using the API key
    client = make_client(url, apikey)

    if client:
        # Retrieve and display the list of available G-code files
        file_names(client)

        # Name of the G-code file that is already uploaded to OctoPrint (adjust this to the correct name)
        gcode_file_name = "final_presentation_demo.g"

        # Select and print the G-code file
        select_and_print_gcode(client, gcode_file_name)